#!/usr/bin/env python
# -*- coding: utf-8 -*-


from PySide import QtGui, QtCore

class MapViewer(QtGui.QWidget):
	def __init__(self, parent=None):
		setParent(parent)
		
	def setBackgroundImage(image):
		
	
